### ISSUE TITLE
Integrate pagination

### ISSUE THREAD

**Issue by Bashamega** [is-a-dev/raw-api#3]
Hello:)
I have noticed that this api just throws all the data at once, which is not the best choice. I was thinking of using express or fastify or nest.js to add pagination to the api

**Comment by wdhdev** [comment]
Hey there, thank you for the idea however that is actually the intended purpose of this API.
The goal of this API is to get all domain data returned at once, as we use this for sites like https://data.is-a.dev.

To be perfectly honest, this isn't even an API, it is literally just a raw JSON file deployed with GitHub Pages. 🤣 

Thanks for your idea thought. In future, if we ever do need this feature we might consider it :)
